version: '2'

services:
    db:
        build: ./docker/mysql
        image: mysql
        volumes:
            - "../recruitment-task-katowice-db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    php:
        build: ./docker/php7
        volumes:
            - .:/msales/recruitment-task-katowice
            - ./logs/recruitment-task-katowice:/msales/recruitment-task-katowice/app/logs
    composer:
        build: ./docker/composer
        volumes_from:
            - php
    nginx:
        build: ./docker/nginx
        ports:
            - 80:80
        volumes_from:
            - php
        depends_on:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx