version: '2'

services:
    db:
        build: ./docker/mysql
        volumes:
            - "../recruitment-task-katowice-db:/var/lib/mysql"
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: user
            MYSQL_PASSWORD: user
    php:
        build: ./docker/php7
        volumes:
            - .:/msales/recruitment-task-katowice
            - ./logs/recruitment-task-katowice:/msales/recruitment-task-katowice/app/logs
    sf:
        build: ./docker/sf
        volumes_from:
            - php
        depends_on:
            - php
    composer:
        build: ./docker/composer
        volumes_from:
            - php
        depends_on:
            - php
    nginx:
        build: ./docker/nginx
        volumes:
            - ./logs/nginx/:/var/log/nginx
        ports:
            - 80:80
        volumes_from:
            - php
        depends_on:
            - php