version: "3"

services:
    php_cli:
        container_name: php_cli.trial
        build: .docker/php-cli
        entrypoint: php
        networks:
            - recruitment-task-katowice
        volumes:
            - .:/msales/recruitment-task-katowice:delegated

    composer:
        container_name: composer.trial
        build: .docker/php-cli
        entrypoint: composer
        networks:
            - recruitment-task-katowice
        volumes:
            - .:/msales/recruitment-task-katowice:delegated

networks:
    recruitment-task-katowice:
        external: true
