version: "3"

services:
    nginx:
        container_name: nginx.trial
        build: .docker/nginx
        volumes:
            - .:/msales/recruitment-task-katowice:delegated
        networks:
            - recruitment-task-katowice
        ports:
            - 8082:80

    php_fpm:
        container_name: php_fpm.trial
        build: .docker/php-fpm
        networks:
            - recruitment-task-katowice
        ports:
            - 9001:9001
        volumes:
            - .:/msales/recruitment-task-katowice:delegated

    mysql:
        container_name: mysql.trial
        build: .docker/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: user
            MYSQL_PASSWORD: user
        networks:
            - recruitment-task-katowice
        ports:
            - 4406:3306

networks:
    recruitment-task-katowice:
        external: true
