FROM php:7.0-fpm

MAINTAINER Marek Szymeczko <marek.szymeczko@msales.com>

RUN apt-get update && apt-get install -y \
    git \
    unzip

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN composer --version

WORKDIR /msales/recruitment-task-katowice

ENTRYPOINT ["composer"]