imports:
    - { resource: config.yml }

framework:
    router:
        resource: '%kernel.root_dir%/config/routing_dev.yml'
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels: ['!event']
        console:
            type: console
            channels: ['!event', '!doctrine']
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info

#swiftmailer:
#    delivery_addresses: ['me@example.com']

guzzle:
    # (de)activate logging/profiler; default: %kernel.debug%
    logging: true
    clients:
        msales:
            base_url: "http://localhost:85/"
            headers:
                Accept: "application/json"

#JUST TO SHOW THAT I CAN CREATE MY OWN CONFIGURATIONS INSIDE A BUNDLE
api:
    advertiser_offers_url: "app_dev.php/advertiser/%d/offers.json"
    # Mapping of advertisers fields, matching the depth of advertisers response
    allowed_fields:
        advertiser_id: ""
        payout_amount: ""
        payout_currency: ""
        name: ""
        countries: ""
        campaign_id: "application_id"
        mobile_platform: "platform"
        app_details:
            platform: "platform"
            bundle_id: "name"
        campaigns:
            countries: "countries"
            points: "payout_amount"
            cid: "application_id"
    # 10 points = $0.001
    points_rate: 0.001
