Recruitment\DomainBundle\Entity\Offer:
  type: entity
  id:
    applicationId:
      type: integer
      unique: true
      generator:
        strategy: AUTO
  fields:
    advertiserId:
      type: integer
      nullable: false
    country:
      type: string
      nullable: false
    payout:
      type: float
      nullable: false
    name:
      type: string
      nullable: false
    platform:
      type: string
      nullable: false