<?php

namespace Recruitment\ApiBundle\Repository;

use Recruitment\ApiBundle\Entity\Offer;

/**
 * OfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param int $applicationId
     *
     * @return mixed
     */
    public function findOrNew(int $applicationId)
    {
        $result = $this->findOneBy(['applicationId' => $applicationId]);

        if (empty($result)) {
            return new Offer();
        }

        return $result;
    }
}
